<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Bem-vindo à Página Inicial</h1>
    <p class="lead">Seu ponto de partida para uma jornada incrível!</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Recursos do Projeto</h2>
            <p>
                Nosso projeto Laminas é uma poderosa estrutura para desenvolvimento web. Com recursos avançados de MVC (Model-View-Controller) e um ambiente de desenvolvimento flexível, você tem tudo o que precisa para construir aplicativos da web de alto desempenho.
            </p>
        </div>
        <div class="col-md-6">
            <h2>Como Começar</h2>
            <p>
                Comece explorando os módulos e funcionalidades disponíveis. Use o menu de navegação acima para acessar diferentes partes do aplicativo. Sinta-se à vontade para personalizar e expandir o projeto de acordo com suas necessidades.
            </p>
        </div>
    </div>
</div>
